version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
#    depends_on:
#      - websocket
#
#  websocket:
#    build:
#      context: .
#      dockerfile: docker/php/Dockerfile
#    command: php websocket.php
#    volumes:
#      - ./src:/var/www/html
