version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  minio-init:
      image: minio/mc
      container_name: minio-init
      depends_on:
        - minio
      entrypoint: >
        /bin/sh -c "
          echo '⏳ Waiting for MinIO...';
          until mc alias set myminio http://minio:9000 minioadmin minioadmin; do
            sleep 2;
          done;
          echo '✅ Connected to MinIO.';
          mc ls myminio;
          if ! mc ls myminio/machinical_memory_landscapes 2>/dev/null; then
            mc mb myminio/machinical_memory_landscapes;
            echo '✅ Bucket created.';
          else
            echo 'ℹ️ Bucket already exists.';
          fi;
        "

#    depends_on:
#      - websocket
#
#  websocket:
#    build:
#      context: .
#      dockerfile: docker/php/Dockerfile
#    command: php websocket.php
#    volumes:
#      - ./src:/var/www/html
