version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - mml-network
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - mml-network

  node:
    image: node:18
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - mml-network
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mml
      MYSQL_USER: mml_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mml-network
    command: --default-authentication-plugin=mysql_native_password

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    networks:
      - mml-network
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  minio-init:
      image: minio/mc
      container_name: minio-init
      depends_on:
        - minio
      networks:
        - mml-network
      entrypoint: >
        /bin/sh -c "
          echo '⏳ Waiting for MinIO...';
          until mc alias set myminio http://minio:9000 minioadmin minioadmin; do
            sleep 2;
          done;
          echo '✅ Connected to MinIO.';
          mc ls myminio;
          if ! mc ls myminio/machinical-memory-landscapes 2>/dev/null; then
            mc mb myminio/machinical-memory-landscapes;
            mc anonymous set download myminio/machinical-memory-landscapes
            echo '✅ Bucket created.';
          else
            echo 'ℹ️ Bucket already exists.';
          fi;
        "

networks:
  mml-network:
    external: true

volumes:
  db-data:
